## 异常状况
- 运行时错误，返回500
- 逻辑错误，如找不到（404），先决条件失败（412）， 无法处理的实体（参数格式不对，422）等

### 为什么需要错误处理
- 防止程序挂掉
- 告诉用户错误信息
- 便于开发者调试

### koa2自带的错误处理
```javascript
ctx.throw(412, "提示的文本")
```

### 自定义catch error
```javascript
app.use(async (ctx, next) => {
  try {
    await next()
  } catch(err) {
    ctx.status = err.status || err.statusCode || 500 // 运行时报错没有code
    ctx.body = {
      message: err.message // 比如程序抛出上面的412错误，此时就会返回{"message": "提示的文本"}的json数据
    }
  }
})
```
